version: '3.8'

services:

  web:
    container_name: web-dev
    restart: always
    build: 
      context: ./web
      dockerfile: Dockerfile_dev
    environment:
     - DEBUG='true'
     - DJANGO_SETTINGS_MODULE=directory.settings.dev
    ports:
     - 8000:8000
    volumes: 
     - ./data/:/data/
     - ./web/:/code/

  client:
    container_name: client-dev
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile_dev
    environment:
      - NODE_ENV=dockerdev
    ports:
      - 3000:3000
    volumes:
     - ./client/:/app/
    stdin_open: true
    depends_on:
      - web